//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pandemica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinic
    {
        public string UniqueID { get; set; }
        public string Title { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string ClinicAddressLine1 { get; set; }
        public string ClinicAddressLine2 { get; set; }
        public string Suburb { get; set; }
        public string state { get; set; }
        public string Postcode { get; set; }
        public string LocationInstructions { get; set; }
        public string DriveThroughTesting { get; set; }
        public string WheelchairAccessible { get; set; }
        public string WalkInAllowed { get; set; }
        public string BookingRequired { get; set; }
        public string BookingLink { get; set; }
        public string BookingPhoneNumber { get; set; }
        public string AgeLimit { get; set; }
        public string ReferralRequired { get; set; }
        public string MondayOpeningHours { get; set; }
        public string MondayBreakStartTime { get; set; }
        public string MondayBreakEndTime { get; set; }
        public string MondayClosingHours { get; set; }
        public string TuesdayOpeningHours { get; set; }
        public string TuesdayBreakStartTime { get; set; }
        public string TuesdayBreakEndTime { get; set; }
        public string TuesdayClosingHours { get; set; }
        public string WednesdayOpeningHours { get; set; }
        public string WednesdayBreakStartTime { get; set; }
        public string WednesdayBreakEndTime { get; set; }
        public string WednesdayClosingHours { get; set; }
        public string ThursdayOpeningHours { get; set; }
        public string ThursdayBreakStartTime { get; set; }
        public string ThursdayBreakEndTime { get; set; }
        public string ThursdayClosingHours { get; set; }
        public string FridayOpeningHours { get; set; }
        public string FridayBreakStartTime { get; set; }
        public string FridayBreakEndTime { get; set; }
        public string FridayClosingHours { get; set; }
        public string SaturdayOpeningHours { get; set; }
        public string SaturdayBreakStartTime { get; set; }
        public string SaturdayBreakEndTime { get; set; }
        public string SaturdayClosingHours { get; set; }
        public string SundayOpeningHours { get; set; }
        public string SundayBreakStartTime { get; set; }
        public string SundayBreakEndTime { get; set; }
        public string SundayClosingHours { get; set; }
        public string SpecialInstructions { get; set; }
        public string ResultsInstructions { get; set; }
        public string ClosureInstructions { get; set; }
        public string AgeRestrictionInstructions { get; set; }
        public string BookingInstructions { get; set; }
        public string OtherInstructions { get; set; }
        public string ProviderWebsite { get; set; }
        public string LastUpdated { get; set; }
    }
}
